
import java.awt.List;
import java.util.ArrayList;
import java.util.Observable;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nemsi
 */
public class HeadQuarters extends javax.swing.JFrame implements Observerble{

    /**
     * Creates new form HeadQuarters
     */
    
    private String name;
    private String message;
    private int num;

    private ArrayList<Observer>observers;
    
    Helicopter helicopter=new Helicopter(this);
    Submarine submarine=new Submarine(this);
    Tank tank=new Tank(this);
    

    public HeadQuarters() {
        initComponents();
        setTitle("HeadQuarters");
        setLocation(0, 0);
        observers=new ArrayList<>();
        observers.add(helicopter);
        observers.add(submarine);
        observers.add(tank);
       
    }
    
    @Override
    public void addObserver(Observer observer){
        observers.add(observer);
    }
    @Override
    public void removeObserver(Observer observer){
        observers.remove(observer);
    }
    
    @Override
    public void getMessage(String message,String name){
        this.message=message;
        this.name=name;
        notifyObservers();
    }
    
    @Override
    public void notifyObservers(){
        for(Observer observer:observers){
                observer.update(this.message,this.name);
        }
    }

    @Override
    public void notifyArea(){
        for(Observer observer:observers){
                observer.update(this.message,this.name);
        }
    }
    
    public void sendMessage(int num) {
        
        if(checkBoxPrivate.isSelected()){
            if(num==0){
                tank.displayArea.append("HeadQuarters : "+txtMsg.getText()+"\n");
            }else if(num==1){
                submarine.displayArea.append("HeadQuarters : "+txtMsg.getText()+"\n");
            }else if(num==2){
                helicopter.displayBody.append("HeadQuarters : "+txtMsg.getText()+"\n");
            }
        }else{
            getMessage(txtMsg.getText(),"HeadQuarters");
        }
        
    }
    
    @Override
    public void isAreaClear(boolean b){
        
        if(b==true){
            helicopter.clearArea.setText("Area Cleared");
            tank.clearArea.setText("Area Cleared");
            submarine.clearArea.setText("Area Cleared");
        }else{
           helicopter.clearArea.setText("Area Not Cleared");
           tank.clearArea.setText("Area Not Cleared");
           submarine.clearArea.setText("Area Not Cleared");
        }    
    }
    
    public void getPosition(int num) {
        
        if(helicopter.isPositioned()){
            helicopter.setPosition(num); 
        }
        
        if(submarine.isPositioned()){
            submarine.setPosition(num); 
        }
        
        if(tank.isPositioned()){
            tank.setPosition(num); 
        }
        
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkAreaClear = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        checkBoxPrivate = new javax.swing.JCheckBox();
        comboBoxItem = new javax.swing.JComboBox();
        btnSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMsg = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayField = new javax.swing.JTextArea();
        positionSlider = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        deployItems = new javax.swing.JComboBox();
        btnDeploy = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        hqAmmoCount = new javax.swing.JLabel();
        hqAmmoCount1 = new javax.swing.JLabel();
        hqAmmoCount2 = new javax.swing.JLabel();
        hqSoliderCount = new javax.swing.JLabel();
        fuelAmount = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Resources");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Soldier Count     :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fuel Amount     :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Ammo Amount  :");

        checkAreaClear.setBackground(new java.awt.Color(255, 255, 255));
        checkAreaClear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        checkAreaClear.setText("Area Cleared");
        checkAreaClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkAreaClear.setFocusable(false);
        checkAreaClear.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkAreaClearItemStateChanged(evt);
            }
        });
        checkAreaClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAreaClearActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Alret Sender");

        checkBoxPrivate.setBackground(new java.awt.Color(255, 255, 255));
        checkBoxPrivate.setText("Send Private");
        checkBoxPrivate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkBoxPrivate.setFocusable(false);
        checkBoxPrivate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPrivateActionPerformed(evt);
            }
        });
        checkBoxPrivate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                checkBoxPrivateKeyReleased(evt);
            }
        });

        comboBoxItem.setEditable(true);
        comboBoxItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tank","Submarine","Helicopter" }));
        comboBoxItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        comboBoxItem.setEnabled(false);
        comboBoxItem.setFocusable(false);
        comboBoxItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxItemActionPerformed(evt);
            }
        });

        btnSend.setBackground(new java.awt.Color(255, 255, 255));
        btnSend.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSend.setText("Send");
        btnSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSend.setFocusable(false);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(txtMsg);

        displayField.setColumns(20);
        displayField.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        displayField.setRows(5);
        displayField.setFocusable(false);
        jScrollPane2.setViewportView(displayField);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnSend, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(checkBoxPrivate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(comboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(114, 114, 114))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap()))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxPrivate)
                    .addComponent(comboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSend))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
        );

        positionSlider.setBackground(new java.awt.Color(255, 255, 255));
        positionSlider.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        positionSlider.setForeground(new java.awt.Color(0, 0, 0));
        positionSlider.setMajorTickSpacing(20);
        positionSlider.setMinorTickSpacing(10);
        positionSlider.setPaintLabels(true);
        positionSlider.setPaintTicks(true);
        positionSlider.setSnapToTicks(true);
        positionSlider.setValue(0);
        positionSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        positionSlider.setFocusable(false);
        positionSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                positionSliderStateChanged(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Position");

        deployItems.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tank", "Submarine", "Helicopter"}));
        deployItems.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deployItems.setFocusable(false);
        deployItems.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deployItemsActionPerformed(evt);
            }
        });

        btnDeploy.setText("Get ");
        btnDeploy.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeploy.setFocusable(false);
        btnDeploy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeployActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Resources Info");

        hqAmmoCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hqAmmoCount.setText("100000");

        hqAmmoCount1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        hqAmmoCount2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        hqSoliderCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hqSoliderCount.setText("100");

        fuelAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fuelAmount.setText("12500");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(checkAreaClear, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(10, 10, 10)
                                .addComponent(hqSoliderCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hqAmmoCount1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(positionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(deployItems, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDeploy))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hqAmmoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fuelAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(hqAmmoCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(442, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkAreaClear)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deployItems, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeploy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(hqAmmoCount1)
                            .addComponent(hqSoliderCount))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fuelAmount))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(hqAmmoCount))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(positionSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(hqAmmoCount2)
                    .addContainerGap(207, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxPrivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPrivateActionPerformed
        // TODO add your handling code here:
        if(checkBoxPrivate.isSelected()){
            comboBoxItem.setEnabled(true);
        }else{
            comboBoxItem.setEnabled(false);
        }
        
        
    }//GEN-LAST:event_checkBoxPrivateActionPerformed

    private void checkBoxPrivateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checkBoxPrivateKeyReleased
        // TODO add your handling code here:    
    }//GEN-LAST:event_checkBoxPrivateKeyReleased

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        sendMessage(num);     
    }//GEN-LAST:event_btnSendActionPerformed

    private void checkAreaClearItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkAreaClearItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAreaClearItemStateChanged

    private void checkAreaClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAreaClearActionPerformed
        // TODO add your handling code here:
        if(checkAreaClear.isSelected()){
            isAreaClear(true);
        }else{
            isAreaClear(false);  
        }
     
    }//GEN-LAST:event_checkAreaClearActionPerformed

    private void comboBoxItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxItemActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==comboBoxItem){
            num=comboBoxItem.getSelectedIndex();
            System.out.println(num);
        }
        
    }//GEN-LAST:event_comboBoxItemActionPerformed

    private void positionSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_positionSliderStateChanged
        // TODO add your handling code here:
        System.out.println(positionSlider.getValue());
        getPosition(positionSlider.getValue());
    }//GEN-LAST:event_positionSliderStateChanged

    private void deployItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deployItemsActionPerformed
        // TODO add your handling code here:
        System.out.println(deployItems.getSelectedIndex());
    }//GEN-LAST:event_deployItemsActionPerformed

    private void btnDeployActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeployActionPerformed
        // TODO add your handling code here:
        if(deployItems.getSelectedIndex()==0){
             tank.sendResourceInfo();
        }else if(deployItems.getSelectedIndex()==1){
            submarine.sendResourceInfo();
        }else{
            helicopter.sendResourceInfo();
        }
    }//GEN-LAST:event_btnDeployActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeadQuarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeadQuarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeadQuarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeadQuarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeadQuarters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeploy;
    private javax.swing.JButton btnSend;
    private javax.swing.JCheckBox checkAreaClear;
    public javax.swing.JCheckBox checkBoxPrivate;
    private javax.swing.JComboBox comboBoxItem;
    private javax.swing.JComboBox deployItems;
    public javax.swing.JTextArea displayField;
    public javax.swing.JLabel fuelAmount;
    public javax.swing.JLabel hqAmmoCount;
    public javax.swing.JLabel hqAmmoCount1;
    public javax.swing.JLabel hqAmmoCount2;
    public javax.swing.JLabel hqSoliderCount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSlider positionSlider;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void powerNotify() {
     
    }

}
