/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author nemsi
 */
public class Tank extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form HeadQuarters
     */
    
    int n;
    
    HeadQuarters hq;
    
    public Tank(HeadQuarters hq) {
        initComponents();
        setTitle("Tank");
        setLocation(690,365);
        this.hq=hq;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        displayArea = new javax.swing.JTextArea();
        clearArea = new javax.swing.JLabel();
        postitonBox = new javax.swing.JCheckBox();
        powerSlider = new javax.swing.JSlider();
        txtMsg = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        btnShoot = new javax.swing.JButton();
        btnMissile = new javax.swing.JButton();
        btnRedar = new javax.swing.JButton();
        btnRotater = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        damageSlider = new javax.swing.JSlider();
        lblDamage = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        soldierCount = new javax.swing.JSpinner();
        lblAmmoCount = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fuelAmount = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        displayArea.setColumns(20);
        displayArea.setRows(5);
        displayArea.setFocusable(false);
        jScrollPane2.setViewportView(displayArea);

        clearArea.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        clearArea.setForeground(new java.awt.Color(255, 0, 0));
        clearArea.setText("Area Not Cleared");

        postitonBox.setBackground(new java.awt.Color(255, 255, 255));
        postitonBox.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        postitonBox.setText("Position");
        postitonBox.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        postitonBox.setFocusable(false);

        powerSlider.setBackground(new java.awt.Color(255, 255, 255));
        powerSlider.setMajorTickSpacing(100);
        powerSlider.setMaximum(1000);
        powerSlider.setMinorTickSpacing(50);
        powerSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        powerSlider.setPaintLabels(true);
        powerSlider.setPaintTicks(true);
        powerSlider.setSnapToTicks(true);
        powerSlider.setValue(1000);
        powerSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        powerSlider.setFocusable(false);

        btnSend.setText("Send");
        btnSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSend.setFocusable(false);
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnShoot.setText("Shoot");
        btnShoot.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnShoot.setEnabled(false);
        btnShoot.setFocusable(false);
        btnShoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShootActionPerformed(evt);
            }
        });

        btnMissile.setText("Missile");
        btnMissile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMissile.setEnabled(false);
        btnMissile.setFocusable(false);
        btnMissile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMissileActionPerformed(evt);
            }
        });

        btnRedar.setText("Redar");
        btnRedar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRedar.setEnabled(false);
        btnRedar.setFocusable(false);

        btnRotater.setText("Rotate Shooting");
        btnRotater.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRotater.setEnabled(false);
        btnRotater.setFocusable(false);
        btnRotater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRotaterActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Power");

        damageSlider.setBackground(new java.awt.Color(255, 255, 255));
        damageSlider.setMajorTickSpacing(20);
        damageSlider.setMinorTickSpacing(10);
        damageSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        damageSlider.setPaintLabels(true);
        damageSlider.setPaintTicks(true);
        damageSlider.setValue(0);
        damageSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        damageSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                damageSliderStateChanged(evt);
            }
        });

        lblDamage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDamage.setText("Damage");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Soldier Count -");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Ammo Count -");

        soldierCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        soldierCount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        soldierCount.setValue(25);
        soldierCount.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                soldierCountStateChanged(evt);
            }
        });

        lblAmmoCount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAmmoCount.setText("25000");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fuel Amount  -");

        fuelAmount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fuelAmount.setText("5000");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(fuelAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(soldierCount, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                            .addComponent(lblAmmoCount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(soldierCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblAmmoCount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fuelAmount)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                        .addGap(94, 94, 94))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clearArea, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRotater)
                                    .addComponent(btnRedar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMissile, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(btnShoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(postitonBox)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDamage, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(damageSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(powerSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(clearArea)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnShoot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMissile, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRedar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRotater)
                                .addGap(26, 26, 26)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(postitonBox)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblDamage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(powerSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3))
                            .addComponent(damageSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        // hq.getMessage(txtMsg.getText(),lblName.getText());
         setMessage(txtMsg.getText());
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnShootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShootActionPerformed
        // TODO add your handling code here:
        int ammo=Integer.parseInt(lblAmmoCount.getText());
        if(ammo>0){
            ammo-=10;  
        }else{
            ammo=0;
        }
        
        lblAmmoCount.setText(Integer.toString(ammo));
        int currentValue=powerSlider.getValue();   
        powerSlider.setValue(currentValue-25);
        
        
    }//GEN-LAST:event_btnShootActionPerformed

    private void btnMissileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMissileActionPerformed
        // TODO add your handling code here:
        int ammo=Integer.parseInt(lblAmmoCount.getText());
        if(ammo>0){
            ammo-=20;  
        }else{
            ammo=0;
        }
        lblAmmoCount.setText(Integer.toString(ammo));
        
        int currentValue=powerSlider.getValue();   
        powerSlider.setValue(currentValue-50);
    }//GEN-LAST:event_btnMissileActionPerformed

    private void btnRotaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRotaterActionPerformed
        // TODO add your handling code here:
        int ammo=Integer.parseInt(lblAmmoCount.getText());
        if(ammo>0){
            ammo-=30;  
        }else{
            ammo=0;
        }
            lblAmmoCount.setText(Integer.toString(ammo));
            
        int currentValue=powerSlider.getValue();   
        powerSlider.setValue(currentValue-100);
    }//GEN-LAST:event_btnRotaterActionPerformed

    private void soldierCountStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_soldierCountStateChanged
        // TODO add your handling code here:
        checkSoliderCount((int)soldierCount.getValue());
    }//GEN-LAST:event_soldierCountStateChanged

    private void damageSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_damageSliderStateChanged
        // TODO add your handling code here:
        if(damageSlider.getValue()==100){
            setAllDisabled();
            setMessage("Tank Got Destroyed !!!");
        }
        
    }//GEN-LAST:event_damageSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeadQuarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeadQuarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeadQuarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeadQuarters.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeadQuarters().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMissile;
    private javax.swing.JButton btnRedar;
    private javax.swing.JButton btnRotater;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnShoot;
    public javax.swing.JLabel clearArea;
    private javax.swing.JSlider damageSlider;
    public javax.swing.JTextArea displayArea;
    private javax.swing.JLabel fuelAmount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAmmoCount;
    private javax.swing.JLabel lblDamage;
    private javax.swing.JCheckBox postitonBox;
    private javax.swing.JSlider powerSlider;
    private javax.swing.JSpinner soldierCount;
    private javax.swing.JTextField txtMsg;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(String text,String name) {
        if("Tank".equals(name)){
            displayArea.append("Me : "+text+"\n");
        }else{
            displayArea.append(name+" : "+text+"\n");
        }
        
        System.out.println(text);
    }

    @Override
    public void setMessage(String message) {
       hq.displayField.append("Tank : "+message+"\n");
       
    }

    @Override
    public boolean isPositioned() {
        return postitonBox.isSelected();
    }

    @Override
    public void setPosition(int value) {
        if(value<=20){
            btnShoot.setEnabled(false);
            btnMissile.setEnabled(false);
            btnRedar.setEnabled(false);
            btnRotater.setEnabled(false);
        }else if(value<=40){
            btnShoot.setEnabled(true);
        }else if(value<=60){
            btnMissile.setEnabled(true);
        }else if(value<=80){
            btnRedar.setEnabled(true);
        }else{
            btnRotater.setEnabled(true);
        }
    }

    @Override
    public void sendResourceInfo() {
        hq.hqAmmoCount.setText(lblAmmoCount.getText());
        hq.fuelAmount.setText(fuelAmount.getText());
        
        int solider=(int)soldierCount.getValue();
         
         if(solider<0){
             hq.hqSoliderCount.setText("0");
         }else{
            hq.hqSoliderCount.setText(solider+"");
         }
    }

    @Override
    public void checkSoliderCount(int soliderCount) {
        
        if(soliderCount<=0){
            setAllDisabled();
            hq.displayField.append("\nTank : All SOLIDERS ARE DEAD ,TANK DOWN !!!\n");
        }
    }

    @Override
    public void setAllDisabled() {
        soldierCount.setEnabled(false);
        btnShoot.setEnabled(false);
        btnMissile.setEnabled(false);
        btnRedar.setEnabled(false);
        btnRotater.setEnabled(false);
        btnSend.setEnabled(false);
        powerSlider.setEnabled(false);
        damageSlider.setEnabled(false);
        txtMsg.setEnabled(false);
        postitonBox.setEnabled(false);
    }


}
